// This file was auto-generated by Fern from our API Definition.

package api

type ChatCompletionsUsageDto struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}
