// This file was auto-generated by Fern from our API Definition.

package api

type ChatCompletionsResponseDto struct {
	Completion *ChatMessageDto          `json:"completion,omitempty"`
	Usage      *ChatCompletionsUsageDto `json:"usage,omitempty"`
}
