// This file was auto-generated by Fern from our API Definition.

package api

type ModelDto struct {
	Name            string `json:"name"`
	VendorName      string `json:"vendor_name"`
	Vendor          string `json:"vendor"`
	TokenLimit      int    `json:"token_limit"`
	MillicentsPer1K int    `json:"millicents_per_1k"`
}
