// This file was auto-generated by Fern from our API Definition.

package api

type ValidationError struct {
	Loc  []*ValidationErrorLocItem `json:"loc,omitempty"`
	Msg  string                    `json:"msg"`
	Type string                    `json:"type"`
}
